package models

type WbnbAutoGenerated struct {
	Wbnb struct {
		Usd float64 `json:"usd"`
	} `json:"wbnb"`
}

type BUSDAutoGenerated struct {
	Busd struct {
		Usd float64 `json:"usd"`
	} `json:"busd"`
}
