package models

type BalanceType int

const(
	LiquidityProvide BalanceType = 0
	Farming BalanceType = 1
	Stake BalanceType = 2
	Lending BalanceType = 3
)

type Explorer struct {
	ID       string
	Name     string
	URL      string
	Standard string
}

type WbnbAutoGenerated struct {
	Wbnb struct {
		Usd float64 `json:"usd"`
	} `json:"wbnb"`
}

type BUSDAutoGenerated struct {
	Busd struct {
		Usd float64 `json:"usd"`
	} `json:"busd"`
}
